{  
   "xAxis":{  
      "categories":[  
         "Jan",
         "Fev",
         "Mar",
         "Abr"
      ],
      "title":{  
         "text":"Saídas"
      }
   },
   "yAxis":{  
      "min":0,
      "title":{  

      }
   },
   "series":[  
      {  
         "name":"Caixa",
         "data":[  
            350,
            580,
            1500,
            130
         ]
      },
      {  
         "name":"Bradesco",
         "data":[  
            123,
            148,
            400,
            758
         ]
      }
   ],
   "chart":{  
      "plotBorderWidth":0,
      "plotShadow":false,
      "options3d":{  
         "enabled":false,
         "alpha":45,
         "beta":0
      },
      "type":"column"
   },
   "title":{  
      "text":"Saídas por conta bancária"
   },
   "subtitle":{  

   },
   "tooltip":{  
      "pointFormat":"\u003c/table\u003e",
      "shared":true,
      "headerFormat":"\u003cspan style\u003d\"font-size:10px\"\u003e{point.key}\u003c/span\u003e\u003ctable\u003e",
      "useHTML":true
   },
   "plotOptions":{  
      "column":{  
         "pointPadding":0.2,
         "borderWidth":0
      }
   },
   "credits":{  
      "enabled":false
   }
}